// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by hive_generator. Run: flutter pub run build_runner build

part of 'word.dart';

// **************************************************************************
// TypeAdapterGenerator
// **************************************************************************

class WordAdapter extends TypeAdapter<Word> {
  @override
  final int typeId = 0;

  @override
  Word read(BinaryReader reader) {
    final numOfFields = reader.readByte();
    final fields = <int, dynamic>{
      for (int i = 0; i < numOfFields; i++) reader.readByte(): reader.read(),
    };
    return Word(
      id: fields[0] as String,
      korean: fields[1] as String,
      english: fields[2] as String,
      level: fields[3] as int,
      partOfSpeech: fields[4] as String,
      example: fields[5] as String,
      exampleTranslation: fields[6] as String,
      pronunciation: fields[7] as String? ?? '',
      category: fields[8] as String? ?? '',
      relatedIds: (fields[9] as List?)?.cast<String>() ?? const [],
    );
  }

  @override
  void write(BinaryWriter writer, Word obj) {
    writer
      ..writeByte(10)
      ..writeByte(0)
      ..write(obj.id)
      ..writeByte(1)
      ..write(obj.korean)
      ..writeByte(2)
      ..write(obj.english)
      ..writeByte(3)
      ..write(obj.level)
      ..writeByte(4)
      ..write(obj.partOfSpeech)
      ..writeByte(5)
      ..write(obj.example)
      ..writeByte(6)
      ..write(obj.exampleTranslation)
      ..writeByte(7)
      ..write(obj.pronunciation)
      ..writeByte(8)
      ..write(obj.category)
      ..writeByte(9)
      ..write(obj.relatedIds);
  }

  @override
  int get hashCode => typeId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WordAdapter &&
          runtimeType == other.runtimeType &&
          typeId == other.typeId;
}
